[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="page" type="com.afterwave.core.bean.Page" --]
[#-- @ftlvariable name="site" type="com.afterwave.config.properties.SiteConfig" --]
[#-- @ftlvariable name="model" type="com.afterwave.core.base.BaseEntity" --]
[#-- @ftlvariable name="topic" type="com.afterwave.module.topic.pojo.Topic" --]
[#-- @ftlvariable name="user" type="com.afterwave.module.user.pojo.User" --]
[#-- @ftlvariable name="comment" type="com.afterwave.module.comment.pojo.Comment" --]
[#-- @ftlvariable name="sec" type="com.afterwave.config.SecurityTag" --]
[#-- @ftlvariable name="log" type="com.afterwave.module.log.pojo.Log" --]
[#-- @ftlvariable name="tag" type="com.afterwave.module.tag.pojo.Tag" --]
